Repository FunDeliveryGames/wow-delve-companion, pull requests merged in 2025-05, with the labels that each got.

#28 New addon settings
  Data/Config.lua
  Data/Enums.lua
  Data/Include.xml
  DelveCompanion_Mainline.toc
  Locale/LockitMain.lua
  Locale/ruRU.lua
  Locale/zhCN.lua
  Locale/zhTW.lua
  Source/Bootstrap.lua
  Source/Core/Main.lua
  Source/Modules/DelvesDashboard/Companion/ConfigWidget.lua
  Source/Modules/DelvesDashboard/DelvesDashboard.lua
  Source/Modules/DelvesDashboard/GreatVault/GreatVaultDetails.lua
  Source/Modules/DelvesDashboard/Overview/Bountiful/BountifulButton.lua
  Source/Modules/DelvesDashboard/Overview/Overview.lua
  Source/Modules/DelvesList/DelvesListFrame.lua
  Source/Modules/DelvesList/ListElements/DelveInstanceButton.lua
  Source/Modules/DelvesList/ListElements/DelveProgressWidget.lua
  Source/Modules/DelvesList/ListElements/DelveProgressWidget.xml
  Source/Modules/TooltipExtension/TooltipExtension.lua
  Source/Settings/Include.xml
  Source/Settings/SettingsFrame.lua
  Source/Settings/SettingsFrame.xml
  Source/Settings/SettingsMain.lua
  Source/Settings/SettingsToggle.lua
  Source/Settings/SettingsToggle.xml
  Source/Utility/DelveTrackingButton.lua
Labels: enhancement, polish

#34 Update zhTW.lua
  Locale/zhTW.lua
Labels: localization

#33 Update RU locale
  DelveCompanion_Mainline.toc
  Locale/ruRU.lua
Labels: localization

#37 V0.6 localization
  DelveCompanion_Mainline.toc
  Locale/LockitMain.lua
  Locale/ruRU.lua
  Locale/zhCN.lua
  Locale/zhTW.lua
Labels: localization

#40 #29: Add addon links to Settings
  Data/Enums.lua
  Locale/LockitMain.lua
  Source/Settings/SettingsFrame.lua
  Source/Settings/SettingsFrame.xml
  Source/Settings/SettingsMain.lua
Labels: enhancement

#42 #29: Add addon links to Settings
  Data/Enums.lua
  Locale/LockitMain.lua
  Source/Settings/SettingsFrame.lua
  Source/Settings/SettingsFrame.xml
  Source/Settings/SettingsMain.lua
Labels: enhancement

#38 Update ruRU.lua
  Locale/ruRU.lua
Labels: localization

#43 Create deDE.lua
  Data/Enums.lua
  DelveCompanion_Mainline.toc
  Locale/Lockit.xml
  Locale/LockitMain.lua
  Locale/deDE.lua
  Source/Settings/SettingsFrame.lua
  Source/Settings/SettingsFrame.xml
  Source/Settings/SettingsMain.lua
Labels: localization

#46 Update ruRU.lua
  Locale/ruRU.lua
Labels: localization
